import { WorkoutProgram } from '@/types';

export const DEFAULT_PROGRAM: WorkoutProgram = {
  id: 'default-ppl',
  name: 'Push Pull Legs',
  createdAt: new Date().toISOString(),
  days: [
    {
      id: 'day-1-push',
      name: 'Push',
      dayNumber: 1,
      isRest: false,
      exercises: [
        { id: 'ex-chest-press', name: 'Chest Press', order: 0 },
        { id: 'ex-incline-press', name: 'Incline Press', order: 1 },
        { id: 'ex-shoulder-press', name: 'Shoulder Press', order: 2 },
        { id: 'ex-tricep-pushdown', name: 'Tricep Pushdown', order: 3 },
        { id: 'ex-cable-lateral-raise', name: 'Cable Lateral Raise', order: 4 },
        { id: 'ex-plank', name: 'Plank', order: 5 },
        { id: 'ex-leg-raises', name: 'Leg Raises', order: 6 },
      ],
    },
    {
      id: 'day-2-pull',
      name: 'Pull',
      dayNumber: 2,
      isRest: false,
      exercises: [
        { id: 'ex-lat-pulldown', name: 'Lat Pulldown', order: 0 },
        { id: 'ex-lat-row', name: 'Lat Row', order: 1 },
        { id: 'ex-biceps-curl', name: 'Biceps Curl', order: 2 },
        { id: 'ex-face-pull', name: 'Face Pull', order: 3 },
        { id: 'ex-dumbbell-shrugs', name: 'Dumbbell Shrugs', order: 4 },
        { id: 'ex-incline-dumbbell-curl', name: 'Incline Dumbbell Curl', order: 5 },
      ],
    },
    {
      id: 'day-3-legs',
      name: 'Legs',
      dayNumber: 3,
      isRest: false,
      exercises: [
        { id: 'ex-leg-press', name: 'Leg Press', order: 0 },
        { id: 'ex-leg-extension', name: 'Leg Extension', order: 1 },
        { id: 'ex-leg-curl', name: 'Leg Curl', order: 2 },
        { id: 'ex-calf-extension', name: 'Calf Extension', order: 3 },
        { id: 'ex-core', name: 'Core', order: 4 },
      ],
    },
    {
      id: 'day-4-push',
      name: 'Push',
      dayNumber: 4,
      isRest: false,
      exercises: [
        { id: 'ex-chest-press-2', name: 'Chest Press', order: 0 },
        { id: 'ex-incline-press-2', name: 'Incline Press', order: 1 },
        { id: 'ex-shoulder-press-2', name: 'Shoulder Press', order: 2 },
        { id: 'ex-tricep-pushdown-2', name: 'Tricep Pushdown', order: 3 },
        { id: 'ex-cable-lateral-raise-2', name: 'Cable Lateral Raise', order: 4 },
        { id: 'ex-plank-2', name: 'Plank', order: 5 },
        { id: 'ex-leg-raises-2', name: 'Leg Raises', order: 6 },
      ],
    },
    {
      id: 'day-5-pull',
      name: 'Pull',
      dayNumber: 5,
      isRest: false,
      exercises: [
        { id: 'ex-lat-pulldown-2', name: 'Lat Pulldown', order: 0 },
        { id: 'ex-lat-row-2', name: 'Lat Row', order: 1 },
        { id: 'ex-biceps-curl-2', name: 'Biceps Curl', order: 2 },
        { id: 'ex-face-pull-2', name: 'Face Pull', order: 3 },
        { id: 'ex-dumbbell-shrugs-2', name: 'Dumbbell Shrugs', order: 4 },
        { id: 'ex-incline-dumbbell-curl-2', name: 'Incline Dumbbell Curl', order: 5 },
      ],
    },
    {
      id: 'day-6-legs',
      name: 'Legs',
      dayNumber: 6,
      isRest: false,
      exercises: [
        { id: 'ex-leg-press-2', name: 'Leg Press', order: 0 },
        { id: 'ex-leg-extension-2', name: 'Leg Extension', order: 1 },
        { id: 'ex-leg-curl-2', name: 'Leg Curl', order: 2 },
        { id: 'ex-calf-extension-2', name: 'Calf Extension', order: 3 },
        { id: 'ex-core-2', name: 'Core', order: 4 },
      ],
    },
    {
      id: 'day-7-rest',
      name: 'Rest',
      dayNumber: 7,
      isRest: true,
      exercises: [],
    },
  ],
};
