import { WorkoutProgram } from '@/types';

export const DEFAULT_PROGRAM: WorkoutProgram = {
  id: 'default-ppl',
  name: 'Push Pull Legs',
  createdAt: new Date().toISOString(),
  exercises: [
    { id: 'ex-chest-press', name: 'Chest Press', order: 0 },
    { id: 'ex-incline-press', name: 'Incline Press', order: 1 },
    { id: 'ex-shoulder-press', name: 'Shoulder Press', order: 2 },
    { id: 'ex-tricep-pushdown', name: 'Tricep Pushdown', order: 3 },
    { id: 'ex-cable-lateral-raise', name: 'Cable Lateral Raise', order: 4 },
    { id: 'ex-plank', name: 'Plank', order: 5 },
    { id: 'ex-leg-raises', name: 'Leg Raises', order: 6 },
    { id: 'ex-lat-pulldown', name: 'Lat Pulldown', order: 7 },
    { id: 'ex-lat-row', name: 'Lat Row', order: 8 },
    { id: 'ex-biceps-curl', name: 'Biceps Curl', order: 9 },
    { id: 'ex-face-pull', name: 'Face Pull', order: 10 },
    { id: 'ex-dumbbell-shrugs', name: 'Dumbbell Shrugs', order: 11 },
    { id: 'ex-incline-dumbbell-curl', name: 'Incline Dumbbell Curl', order: 12 },
    { id: 'ex-leg-press', name: 'Leg Press', order: 13 },
    { id: 'ex-leg-extension', name: 'Leg Extension', order: 14 },
    { id: 'ex-leg-curl', name: 'Leg Curl', order: 15 },
    { id: 'ex-calf-extension', name: 'Calf Extension', order: 16 },
    { id: 'ex-core', name: 'Core', order: 17 },
  ],
  days: [
    {
      id: 'day-1-push',
      name: 'Push',
      dayNumber: 1,
      isRest: false,
      exercises: [
        { exerciseId: 'ex-chest-press', order: 0 },
        { exerciseId: 'ex-incline-press', order: 1 },
        { exerciseId: 'ex-shoulder-press', order: 2 },
        { exerciseId: 'ex-tricep-pushdown', order: 3 },
        { exerciseId: 'ex-cable-lateral-raise', order: 4 },
        { exerciseId: 'ex-plank', order: 5 },
        { exerciseId: 'ex-leg-raises', order: 6 },
      ],
    },
    {
      id: 'day-2-pull',
      name: 'Pull',
      dayNumber: 2,
      isRest: false,
      exercises: [
        { exerciseId: 'ex-lat-pulldown', order: 0 },
        { exerciseId: 'ex-lat-row', order: 1 },
        { exerciseId: 'ex-biceps-curl', order: 2 },
        { exerciseId: 'ex-face-pull', order: 3 },
        { exerciseId: 'ex-dumbbell-shrugs', order: 4 },
        { exerciseId: 'ex-incline-dumbbell-curl', order: 5 },
      ],
    },
    {
      id: 'day-3-legs',
      name: 'Legs',
      dayNumber: 3,
      isRest: false,
      exercises: [
        { exerciseId: 'ex-leg-press', order: 0 },
        { exerciseId: 'ex-leg-extension', order: 1 },
        { exerciseId: 'ex-leg-curl', order: 2 },
        { exerciseId: 'ex-calf-extension', order: 3 },
        { exerciseId: 'ex-core', order: 4 },
      ],
    },
    {
      id: 'day-4-push',
      name: 'Push',
      dayNumber: 4,
      isRest: false,
      exercises: [
        { exerciseId: 'ex-chest-press', order: 0 },
        { exerciseId: 'ex-incline-press', order: 1 },
        { exerciseId: 'ex-shoulder-press', order: 2 },
        { exerciseId: 'ex-tricep-pushdown', order: 3 },
        { exerciseId: 'ex-cable-lateral-raise', order: 4 },
        { exerciseId: 'ex-plank', order: 5 },
        { exerciseId: 'ex-leg-raises', order: 6 },
      ],
    },
    {
      id: 'day-5-pull',
      name: 'Pull',
      dayNumber: 5,
      isRest: false,
      exercises: [
        { exerciseId: 'ex-lat-pulldown', order: 0 },
        { exerciseId: 'ex-lat-row', order: 1 },
        { exerciseId: 'ex-biceps-curl', order: 2 },
        { exerciseId: 'ex-face-pull', order: 3 },
        { exerciseId: 'ex-dumbbell-shrugs', order: 4 },
        { exerciseId: 'ex-incline-dumbbell-curl', order: 5 },
      ],
    },
    {
      id: 'day-6-legs',
      name: 'Legs',
      dayNumber: 6,
      isRest: false,
      exercises: [
        { exerciseId: 'ex-leg-press', order: 0 },
        { exerciseId: 'ex-leg-extension', order: 1 },
        { exerciseId: 'ex-leg-curl', order: 2 },
        { exerciseId: 'ex-calf-extension', order: 3 },
        { exerciseId: 'ex-core', order: 4 },
      ],
    },
    {
      id: 'day-7-rest',
      name: 'Rest',
      dayNumber: 7,
      isRest: true,
      exercises: [],
    },
  ],
};
